### Production environment settings

# STS role and target account
sts_role_arn: arn:aws:iam::543279062384:role/admin

# Network settings
config_vpc_name: default
config_az_count: 1

# Application settings
config_application_ami: ami-b4ce76d4
config_application_instance_type: t2.micro
config_application_keyname: docker-production-aws

# Proxy settings
config_proxy_image: 543279062384.dkr.ecr.us-west-2.amazonaws.com/dockerproductionaws/squid
config_proxy_whitelist: ".dockerproductionaws.org"